// Phys1Syllabus.js
// Export  initial Physics 1 syllabus object

export default  Phys1Syllabus ={
    ShortName: "Phys1",
    SchoolName: "Gavilan College",
    CourseName: "Physics 1: Introduction to Physics",
    CourseLink: "https://mrocha.org/phys1",
    SectionCode: "10378 - PHYS 1 - 701",
    SectionLink: "https://ssb.gavilan.edu/prod/bwckschd.p_disp_detail_sched?term_in=201770&crn_in=10378",
    Term: "Fall 2017",
    Units: "4",
    Room: "Phys Sci 102",
    Time: "TR 2:30-5:30 pm",
    OfficeHour: "Thursdays 5:30-6:30 pm",
    InstructorName: "Miguel E. Rocha",
    InstructorEmail: "mrocha@gavilan.edu",
    RequiredText: "Conceptual Physics 12th Edition by Paul G. Hewitt",
    CourseDescription: "This course is an introduction to the fundamental physical principles that control the world around us. Students will explore the fundamental principles of physics, their historical development, their application to everyday phenomena, and their impact upon political, social, and environmental issues. Laboratory exercises will explore the everyday world. ADVISORY: Mathematics 430. ",
    CourseMotive: {mrocha:"Physics is all about trying to understand the mysteries of the universe, and after each discovery realize how much more there is to know.", heisenberg:"Not only is the Universe stranger than we think, it is stranger than we can think."},    
    LearningObjectives: [
	"Identify, describe, compare and contrast the various units of numbers and their significance.",
	"Identify, describe, compare and contrast random and systematic errors.",
	"Describe the Scientific Method.",
	"Identify, describe, compare and contrast distance, displacement, speed, velocity and acceleration.",
	"Identify, describe, compare and contrast forces, Newton's Laws, conservation of momentum, conservation of energy, power, and work.",
	"Describe the structure of an atom.",
	"Identify, describe, compare and contrast the structure of and differences between various states of matter.",
	"Describe, compare and contrast temperature, heat energy, heat transfer, and the first and second Laws of Thermodynamics.",
	"Describe, identify, compare and contrast longitudinal, transverse, sound, and light waves",
	 "Describe, compare and contrast electric and magnetic fields, resistance, current, and voltage."	
    ],
    CourseSchedule:{
	"week 1":["Chapters: 1", "<a href='http://slides.com/migroch/deck-2-4/fullscreen' target='_blank'>Lecture Slides</a>"],
	"week 2":["Chapters: 2, 3, 4, 5", "<a href='http://slides.com/migroch/deck-1-3-5/fullscreen' target='_blank'>Lecture Slides</a>","<a href='Phys1-HW1andLab1.pdf' target='_blank'>HW/Lab 1</a> due Thursday"],
	"week 3":["Chapters: 6, 7", "<a href='http://slides.com/migroch/deck-1-3-7/fullscreen' target='_blank'>Lecture Slides</a>", "<a href='https://ilearn.gavilan.edu/courses/2425/assignments/19079' target='_blank'>HW 2</a>, <a href='Lab-WalkingThePlank.pdf' target='_blank'>Lab 2</a> and <a href='TerminalVelocityLab.pdf' target='_blank'>Lab 3</a> due Thursday" ],
	"week 4":["Chapters: 8, 9, 10", "<a href='https://slides.com/migroch/deck-2-4-9/fullscreen' target='_blank'>Rotational Motion Slides</a>, <a href='https://slides.com/migroch/deck-1-3-7-11/fullscreen' target='_blank'>Gravity and Projectile Motion Slides</a>","<a href='https://ilearn.gavilan.edu/courses/2425/assignments/19395' target='_blank'>HW 3</a>, <a href='Lab4_ConservationOfMomentum.pdf' target='_blank'>Lab 4</a> and <a href='Lab5_ConservationOfEnergy.pdf' target='_blank'>Lab 5</a> due Thursday"],
	"week 5":[ "<a href='Phys1-Midterm1.pdf' target='_blank'>Mid Term (Ch 1-10)</a>"],
	"week 6":["Chapters: 11-14", "<a href='https://slides.com/migroch/deck-1-3-7-11-13/fullscreen' target='_blank'>Lecture Slides</a", "<a href='https://ilearn.gavilan.edu/courses/2425/assignments/19760' target='_blank'>HW 4</a> and <a href='Lab6_RotationalInertia.pdf' target='_blank'>Lab 6</a> due Tuesday"],
	"week 7":["Chapters: 15-18", "<a href='https://ilearn.gavilan.edu/courses/2425/assignments/20667' target='_blank'>HW 5</a>, <a href='Lab7_Questionnaire.pdf' target='_blank'>Lab 7 Questionnaire</a>,  <a href='Phys1-Lab8.pdf' target='_blank'>Lab 8</a> due Thursday"],
	"week 8":["Chapters: 19-21", "HW 6, <a href='Phys1-Lab9.pdf' target='_blank'>Lab 9</a> due Thursday"],
	"week 9":["Chapters: 22-23", "HW/Lab due"],
	"week 10":["Chapters: 24-25", "HW/Lab due",  "Mid Term (Ch 11-21)"],
	"week 11":["Chapters: 26-28", "HW/Lab  due"],
	"week 12":["Chapters: 29-31", "HW/Lab  due"],
	"week 13":["Chapters: 32-34", "HW/Lab  due"],
	"week 14":["Chapters: 35-36", "HW/Lab due"],
	//"week 15":["Chapters: 35, 36", "HW/Lab due"],
	"week 15":["HW/Lab 15 due", "Final (Ch 22-34)"]
    },
    Homework:"Your homeworks and lab reports are due Thursdays at 6:30 pm",
    Labs:"You must get your data on the designated lab hours, NO MAKEUP LABS!",
    Projects:"None",
    Grading:{"Homework":"20%", "Lab Reports":"20%", "Exams":"20% each, 60% Total"},
    GradeScale:"https://i0.wp.com/greatcollegeadvice.com/wp-content/uploads/2008/11/slide15.jpg",
    ExtraCredit:"There will be extra credit oportunities within your homeworks, labs and lectures",
    SuccessTip:"READ the text book, do not memorize, UNDERSTAND!",
    Honesty:"Students are expected to exercise academic honesty and integrity. Violations such as cheating and plagiarism will result in disciplinary action which may include recommendation for dismissal.",
    AttendancePolicy:"Students missing one more class hour than the unit value for particular course, without making prior arrangements may, at the instructor’s option, be dropped without possibility of credit.",
    ADA:"Students requiring special services or arrangements because of hearing, visual, or other disability should contact their instructor, counselor, or the Disability Resource Center.",
    OV:"Occupational/Vocational students—Limited English language skills will not be a barrier to admittance to and participation in Vocational Education Programs."
};
